# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_nTry',
                'doc_host': 'https://directysj.github.io',
                'git_url': 'https://github.com/directysj/nbdev_nTry',
                'lib_path': 'nbdev_nTry'},
  'syms': {'nbdev_nTry.core': {'nbdev_nTry.core.foo': ('core.html#foo', 'nbdev_nTry/core.py')}}}